import {Course} from './Course'
export const COURSES:Course[]=[
    {
    title: 'HTML101',
    level: 'Beginner',
    rating: '5',
    language: 'English',
    instructor:'Mosh Hamdani',
    discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
    price:'250$',
    outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
    topic:'HTML',
    studentsEnrolled:35,
    image:'./assets/images/teach5.jpg',
    id:1
    },
    {
        title: 'HTML102',
        level: 'Intermediate',
        rating: '4',
        language: 'French',
        instructor:'La Rosha',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'450$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'HTML',
        studentsEnrolled:35,
        image:'./assets/images/teach.jpg',
        id:2
    },
    {
        title: 'CSS101',
        level: 'Beginner',
        rating: '5',
        language: 'English',
        instructor:'Albert Berkley',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'150$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'CSS',
        studentsEnrolled:35,
        image:'./assets/images/teach3.png',
        id:0
    },
    {
        title: 'Angular101',
        level: 'Expert',
        rating: '5',
        language: 'English',
        instructor:'Sarah James',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'210$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'Angular Js',
        studentsEnrolled:35,
        image:'./assets/images/teach8.png',
        id:9
    },
    {
        title: 'Angular102',
        level: 'Expert',
        rating: '5',
        language: 'Urdu',
        instructor:'Dr Khan',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'460$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'Angular Js',
        studentsEnrolled:35,
        image:'./assets/images/teach2.jpg',
        id:3
    },
    {
        title: 'Bootstrap101',
        level: 'Beginner',
        rating: '4',
        language: 'Urdu',
        instructor:'Miss Laiba Khan',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'250$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'Bootstrap',
        studentsEnrolled:35,
        image:'./assets/images/teach4.jpg',
        id:4
    },
    {
        title: 'MVC101',
        level: 'Beginner',
        rating: '4',
        language: 'English',
        instructor:'Nigel Kelly',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'400$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'MVC',
        studentsEnrolled:35,
        image:'./assets/images/teach5.jpg',
        id:5
    },
    {
        title: 'MVC102',
        level: 'Expert',
        rating: '2',
        language: 'French',
        instructor:'Stever Ky',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'250$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'MVC',
        studentsEnrolled:35,
        image:'./assets/images/teach6.jpg',
        id:6
    },
    {
        title: 'MVC103',
        level: 'Intermediate',
        rating: '4',
        language: 'French',
        instructor:'De Hebnz',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'250$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'HTML',
        studentsEnrolled:35,
        image:'./assets/images/teach7.jpg',
        id:7
     },
     {
        title: 'MEAN103',
        level: 'Beginner',
        rating: '3',
        language: 'English',
        instructor:'Oscar Morales',
        discountinfo:'Drop an email at courseprovider.discount@gmail.com for discount info',
        price:'250$',
        outline:'This course will appeal to a wide variety of people, but specifically those who would like a step-by-step description of the basics. There are no prerequisites for this course and it is assumed that students have no prior programming skills or IT experience. The course will culminate in a small final project that will require the completion of a very simple page with links and images. The focus of this course is on the basics, not appearance. ',
        topic:'MEAN Stack',
        studentsEnrolled:35,
        image:'./assets/images/teach2.jpg',
        id:8
    }


]